#!/bin/bash


SCHEMEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. $SCHEMEDIR/scheme_utils

SCHEME_DATE_FMT="%a %b %d %Y %-I:%M %p %Z"

function show_scheme_header {
	printf '%s' "$(scheme_bar "$myblue$HOSTNAME$myreset" "$(date +"$SCHEME_DATE_FMT")" "$(battery_perc --ascii --color)")"
}

#alias clear='tput cup 1 0 && tput ed'

PROMPT_COMMAND=show_scheme_header

PS1='\u \['$myblue'\][\w]\['$myreset'\]$(if git_dirty; then printf "\[${myyellow}\]$(find_git_branch)"; else printf "\[$mygreen\]$(find_git_branch)";fi)\['$myreset'\] '

