#!/bin/sh


alias clear='tput cup 1 0 && tput ed'

function print_header {
	stty size | {
		read y x
		tput sc
	
		# path breadcrumbs on the left
		tput cup 0 0		
		tput el  # clear line
		printf '\e[1;34m[%s]\e[m' $(pwd -P | sed "s;$HOME;~;")
		
		# hostname in center of the screen
		TITLE="$(whoami)@$HOSTNAME"
		tput cup "0" "$(( (x - ${#TITLE}) / 2 ))"  
		printf '\e[0;32m%s\e[m' "$TITLE"
		
		# time in the top right of the screen
		D=$(date)
		tput cup "0" "$((x - ${#D}-1))"  
		printf %s "$D"
		
		tput rc
	}
}


function branch_finder {
	M=$(git branch 2> /dev/null | grep \* | sed '{s/*// ; s/ //}') 
	if [[ "$M" != "" ]]; then
		echo -e "\e[0;32m($M)\e[m "
	else
		echo -e "\e[0;32m>\e[m "
	fi
}

PS1='\u \e[1;34m[\w]\e[m `branch_finder``print_header` '

